name: CI
on:
  pull_request:
    branches:
      - main
      - 'rc**'
jobs:
  test:
    name: Module Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
        env:
            PLATFORM: ${{ env.HUBBLE_DEMO_PLATFORM }}
            PLATFORM_BASE_URL: ${{ env.HUBBLE_DEMO_PLATFORM_BASE_URL }}
            API_BASE_URL: ${{ env.HUBBLE_DEMO_API_BASE_URL }}
            API_SW_ACCESS_KEY: ${{ env.HUBBLE_DEMO_API_SW_ACCESS_KEY }}

