name: CI

on:
  pull_request:
    branches:
      - main
      - 'rc**'

env:
  PLATFORM: ${{ vars.HUBBLE_DEMO_PLATFORM }}
  PLATFORM_BASE_URL: ${{ vars.HUBBLE_DEMO_PLATFORM_BASE_URL }}
  API_BASE_URL: ${{ vars.HUBBLE_DEMO_API_BASE_URL }}
  API_SW_ACCESS_KEY: ${{ vars.HUBBLE_DEMO_API_SW_ACCESS_KEY }}

jobs:
  test:
    name: Module Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Prepare tsconfig for tests
        run: rm ./tsconfig.json && cp ./tsconfig-tests.json ./tsconfig.json

      - name: Run integration tests
        run: npm run test:integration

      - name: Run e2e tests
        run: npm run test:e2e
